### ISSUE TITLE
Redacción del documento de situación del Milestone 2

### ISSUE THREAD

**Issue by jorgegarciax2** [Proyecto-EGC-G1/RedesSociales-EGC-G1#14]
Cumplimentar el documento que ha de presentarse en el  Milestone 2.

**Comment by migcarde** [comment]
Realizada el documento de situación del Milestone 2 y entregado el 14/12/2017. En dicho documento se detallan los siguientes puntos:
- Situación del proyecto y dificultades del mismo.
- Redacción de cambios que se van a realizar en el proyecto.
- Explicación del proceso de gestión del código fuente y de incidencias.
