### ISSUE TITLE
Investigación de creación y montado del sistema Wordpress en Docker

### ISSUE THREAD

**Issue by dominguezvazquezdavid** [Proyecto-EGC-G1/RedesSociales-EGC-G1#18]
Investigación y desarrollo para montar Wordpress y MySQL en Docker.

**Comment by dominguezvazquezdavid** [comment]
Avance: Conseguido montar y realizar el dump en una base de datos MySQL.

**Comment by dominguezvazquezdavid** [comment]
Avance: Conseguido montar y realizar el dump automáticamente en la base de datos MySQL.

**Comment by dominguezvazquezdavid** [comment]
Avance: Conseguido montar tanto MySQL como Wordpress del congreso, pero sigo teniendo problemas para cambiar la ip a localhost.

**Comment by jorgegarciax2** [comment]
**La tarea esta esta duplicada con otra creada hace tiempo. Marco la otra como duplicada y procedo a su cierre puesto que esta contiene mas información del avance de la misma. La tarea en cuestión es: #5 ¿te parece correcto @dominguezvazquezdavid ? **

**Comment by dominguezvazquezdavid** [comment]
me parece correcto.
