### ISSUE TITLE
Creación de la presentación del milestone 2

### ISSUE THREAD

**Issue by EusebioG96** [Proyecto-EGC-G1/RedesSociales-EGC-G1#20]
Creación de la presentación en formato Pecha Kucha para el milestone 2.
Consistirá en una presentación con 20 diapositivas con una duración de 20 segundos cada una.

**Comment by jorgegarciax2** [comment]
La presentación es para el milestone 2 @EusebioG96

**Comment by EusebioG96** [comment]
Corregido título, comentario y milestone puesto que no eran correctos.
