### ISSUE TITLE
Investigación sobre el uso de JavaScript para la visualización de publicaciones

### ISSUE THREAD

**Issue by migcarde** [Proyecto-EGC-G1/RedesSociales-EGC-G1#3]
Realización de una investigación sobre como visualizar las publicaciones de un perfil de facebook siempre que sean públicas.

**Comment by migcarde** [comment]
No se ha encontrado una forma viable de implementar la API de Facebook en nuestro proyecto.

**Comment by jorgegarciax2** [comment]
Aporta más detalles, indica que es exactamente lo que no podemos hacer. Tal y como vimos si que podríamos visualizar el contenido de una página sin estar autenticados en el sistema. @migcarde

**Comment by migcarde** [comment]
Disculpa la confusión, es cierto que lo vimos y en la discusión estábamos discutiendo sobre la API de instagram. Dejo la tarea abierta entonces y sigo investigando sobre el tema. @jorgegarciax2

**Comment by migcarde** [comment]
Se reanuda la tarea al ser necesario javascript para realizar acciones de click e introducir valores en formularios.

**Comment by migcarde** [comment]
Se ha finalizado la investigación y se ha conseguido realizar un post a la página de facebook de los congresos con un token de acceso de larga duración y el sdk de facebook para JavaScript.
