### ISSUE TITLE
investigacion

### ISSUE THREAD

**Issue by hannacheikh11** [Proyecto-EGC-G1/RedesSociales-EGC-G1#8]
compartir los resultados de votos en los redes sociales mediante un grafica de resultados untilizando php y javasript y  MySQL

**Comment by jorgegarciax2** [comment]
Este issue **no cumple con el estándar preestablecido**. El issue debe estar asociado a un proyecto y con alguna etiqueta identificativa. Además el titulo no ofrece la información necesaria.

**¿ @hannacheikh11 , es este issue el mismo que el #9 ?** Si es así, procederé al cierre.

**Comment by jorgegarciax2** [comment]
Tras no obtener respuesta en 3 días y bajo la nueva normativa de creación de incidencias, cierro la tarea por no cumplir los procedimientos de creación de incidencias.
