### ISSUE TITLE
Investegación sobre compartir los resultados en los redes sociales

### ISSUE THREAD

**Issue by hannacheikh11** [Proyecto-EGC-G1/RedesSociales-EGC-G1#9]
Investegación sobre compartir los resultados en las redes sociales utilizando javascript y php

**Comment by migcarde** [comment]
Con esta investigación queríamos compartir los resultados de las votaciones en instagram a base de subir fotos a dicha red social con los resultados de las votaciones entre otro tipo de información de interés, además de poder visualizar las fotos en la página web a modo de widged. Sin embargo, tras la investigación hemos visto que no es posible subir dichas fotos a través de la api si se considera que se hace desde un ordenador, por lo que el rol de la API en nuestro proyecto sería costoso y de poca utilidad. Por lo tanto, se ha decidido cerrar esta issue.

**Comment by hannacheikh11** [comment]
ya he conseguido todo lo que necisatmos
